const REQUEST_SUCCEDED = 200;
const RESOURCE_CREATED = 201;
const NOT_FOUND = 404;
const INVALID_DATA = 400;
const INTERNAL_SERVER_ERROR = 500;

module.export = { REQUEST_SUCCEDED, RESOURCE_CREATED, NOT_FOUND, INVALID_DATA, INTERNAL_SERVER_ERROR };